[package]
name = "OxideMC"
version = "0.0.8"
edition = "2021"

[[bin]]
name = "oxidemc"
path = "src/main.rs"

[dependencies]
cliclack = "0.3.9"
reqwest = { version = "0.13.2", features = ["blocking"] }
serde_json = "1.0.149"
dirs = "6.0"
