[package]
name = "ServerSetup"
version = "0.1.0"
edition = "2024"

[dependencies]
cliclack = "0.3.9"
futures-util = "0.3.32"
reqwest = { version = "0.13.2", features = ["blocking", "stream"] }
serde_json = "1.0.149"
tokio = {version = "1.49.0", features = ["full"] }
shellexpand = "3.1"
